# Generated by Django 5.2.7 on 2025-11-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_blog_user_alter_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookHighlight',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('document_id', models.CharField(default='epub-book', max_length=255)),
                ('document_title', models.CharField(default='EPUB Book', max_length=500)),
                ('chapter_number', models.IntegerField()),
                ('chapter_title', models.CharField(blank=True, max_length=500)),
                ('highlighted_text', models.TextField()),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('purple', 'Purple')], default='yellow', max_length=20)),
                ('start_offset', models.IntegerField(default=0)),
                ('end_offset', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookHighlightComment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.bookhighlight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_highlight_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bookhighlight',
            index=models.Index(fields=['user', 'document_id'], name='api_bookhig_user_id_0ca473_idx'),
        ),
        migrations.AddIndex(
            model_name='bookhighlight',
            index=models.Index(fields=['document_id', 'chapter_number'], name='api_bookhig_documen_f79357_idx'),
        ),
        migrations.AddIndex(
            model_name='bookhighlight',
            index=models.Index(fields=['created_at'], name='api_bookhig_created_8e9f3a_idx'),
        ),
    ]
