# Generated by Django 5.2.7 on 2025-11-04 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bookhighlight_bookhighlightcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('document_id', models.CharField(max_length=255)),
                ('current_chapter', models.IntegerField(default=1)),
                ('scroll_position', models.IntegerField(default=0)),
                ('total_chapters', models.IntegerField(default=1)),
                ('reading_time_minutes', models.IntegerField(default=0)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read_at'],
                'indexes': [models.Index(fields=['user', 'document_id'], name='api_reading_user_id_b46fb5_idx'), models.Index(fields=['session_key', 'document_id'], name='api_reading_session_dd0745_idx'), models.Index(fields=['last_read_at'], name='api_reading_last_re_622617_idx')],
                'unique_together': {('session_key', 'document_id'), ('user', 'document_id')},
            },
        ),
    ]
